services:
  bot:
    container_name: checkinzzz-bot
    build:
      context: .
      target: prod
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./data:/app/data
    stop_grace_period: 1m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
